//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.SuatChieux = new HashSet<SuatChieu>();
        }

        [DisplayName("Mã phim")]
        public int maphim { get; set; }
        [DisplayName("Mã thể loại")]
        public int matheloai { get; set; }
        [DisplayName("Đạo diễn")]
        public string daodien { get; set; }
        [DisplayName("Tên phim")]
        public string tenphim { get; set; }
        [DisplayName("Ngày khởi chiếu")]
        public System.DateTime ngaykhoichieu { get; set; }
        [DisplayName("Ngày kết thúc")]
        public System.DateTime ngayketthuc { get; set; }
        [DisplayName("Mô tả")]
        public string mota { get; set; }
        [DisplayName("Hình")]
        public string hinh { get; set; }
        [DisplayName("Nhà sản xuất")]
        public string nhasanxuat { get; set; }
        [DisplayName("Thời lượng")]
        public int thoiluong { get; set; }
        [DisplayName("Trailer")]
        public string trailer { get; set; }
        [DisplayName("Thể loại")]
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu> SuatChieux { get; set; }
    }
}
