//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ve
    {
        [DisplayName("Mã vé")]
        public int mave { get; set; }
        [DisplayName("Mã suất chiếu")]
        public int masuatchieu { get; set; }
        [DisplayName("Mã khách hàng")]
        public Nullable<int> makhachhang { get; set; }
        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [DisplayName("Giá vé")]
        public int giave { get; set; }
        [DisplayName("Tình trạng")]
        public bool tinhtrang { get; set; }
        [DisplayName("Giờ đặt")]
        public Nullable<System.DateTime> giodat { get; set; }
        [DisplayName("Mã loại vé")]
        public int maloaive { get; set; }
        [DisplayName("Mã khuyến mãi")]
        public Nullable<int> makm { get; set; }
        [DisplayName("Khách hàng")]
        public virtual KhachHang KhachHang { get; set; }
        [DisplayName("Khuyến mãi")]
        public virtual KhuyenMai KhuyenMai { get; set; }
        [DisplayName("Loại vé")]
        public virtual LoaiVe LoaiVe { get; set; }
        [DisplayName("Suất chiếu")]
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
