//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class VeDangDat
    {
        [DisplayName("Mã vé")]
        public int mave { get; set; }
        [DisplayName("Mã suất chiếu")]
        public int masuatchieu { get; set; }
        [DisplayName("Mã khách hàng")]
        public int makhachhang { get; set; }
        [DisplayName("Giá vé")]
        public int giave { get; set; }
        [DisplayName("Tình trạng")]
        public bool tinhtrang { get; set; }
        [DisplayName("Giờ đặt")]
        public System.DateTime giodat { get; set; }
        [DisplayName("Mã loại vé")]
        public int maloaive { get; set; }
        [DisplayName("Mã khuyến mãi ")]
        public Nullable<int> makm { get; set; }
    }
}
